// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM8jZB0jN9wUcG_0k1bzZ34eUQPGPyUk0',
    appId: '1:1017907034066:web:ef96164a0188a6f32cba0b',
    messagingSenderId: '1017907034066',
    projectId: 'startupbridge-4c5de',
    authDomain: 'startupbridge-4c5de.firebaseapp.com',
    storageBucket: 'startupbridge-4c5de.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0hiVyEWkII8zLvwoMY4KzmIzYmpIzp_U',
    appId: '1:1017907034066:android:8dfffbaf6d7bcd382cba0b',
    messagingSenderId: '1017907034066',
    projectId: 'startupbridge-4c5de',
    storageBucket: 'startupbridge-4c5de.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxaeSu83l7YpQNFeQkxx6D0N_p8UfjrnI',
    appId: '1:1017907034066:ios:fa5d0255c4c532492cba0b',
    messagingSenderId: '1017907034066',
    projectId: 'startupbridge-4c5de',
    storageBucket: 'startupbridge-4c5de.firebasestorage.app',
    iosBundleId: 'com.example.startupBridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxaeSu83l7YpQNFeQkxx6D0N_p8UfjrnI',
    appId: '1:1017907034066:ios:fa5d0255c4c532492cba0b',
    messagingSenderId: '1017907034066',
    projectId: 'startupbridge-4c5de',
    storageBucket: 'startupbridge-4c5de.firebasestorage.app',
    iosBundleId: 'com.example.startupBridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM8jZB0jN9wUcG_0k1bzZ34eUQPGPyUk0',
    appId: '1:1017907034066:web:957b8b287c2301212cba0b',
    messagingSenderId: '1017907034066',
    projectId: 'startupbridge-4c5de',
    authDomain: 'startupbridge-4c5de.firebaseapp.com',
    storageBucket: 'startupbridge-4c5de.firebasestorage.app',
  );
}
